package sherlock.ui;

import java.util.Scanner;

/**
 * Handles all console input and output for Sherlock.
 */
public class Ui implements AutoCloseable {
    private static final String BANNER = "  ____  _               _            _    \n"
            + " / ___|| |__   ___ _ __| | ___   ___| | __\n"
            + " \\___ \\| '_ \\ / _ \\ '__| |/ _ \\ / __| |/ /\n"
            + "  ___) | | | |  __/ |  | | (_) | (__|   < \n"
            + " |____/|_| |_|\\___|_|  |_|\\___/ \\___|_|\\_\\\n";
    private final Scanner scanner;

    /**
     * Creates a text user interface that reads commands from the given scanner.
     *
     * @param scanner command input source
     */
    public Ui(Scanner scanner) {
        this.scanner = scanner;
    }

    /**
     * Reads one full command from the user.
     *
     * @return entered command text
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /** Displays Sherlock's greeting. */
    public void showWelcome() {
        System.out.println(BANNER);
        System.out.println("Hello! I'm Sherlock, your detective assistant.");
        System.out.println("What can I do for you?");
    }

    /** Displays one complete response generated by Sherlock. */
    public void showResponse(String response) {
        System.out.println(response);
    }

    /** Displays an error that occurred while loading saved tasks. */
    public void showLoadingError(String message) {
        System.out.println("☹ OOPS!!! I could not load saved tasks: " + message);
    }

    /** Closes the scanner used by this user interface. */
    @Override
    public void close() {
        scanner.close();
    }
}
